### ISSUE TITLE
안녕하세용

### ISSUE THREAD

**Issue by dmjeong** [gellston/FIAT#1]
이 프로젝트 nuget들이 복구가 안되는데 혹시 어떻게 해야 할까요?

감사합니다!

**Comment by gellston** [comment]
안녕하세요 지금 봤네요
관심 가져주셔서 감사 하구요. 
지금 코드는 다 공개인데 사용하고있는 라이브러리 중에 유로 라이센스 등록된 devexpress를 사용하고있어요
어느정도 기능이 다 갖춰지면 제가 프로그램 배포를 해서 공유를 드릴려고하거든요. 
만약에 빌드를 원하신다면 유료 devexpress가 필요하실거구.. 무료로 체험판같은거 설치하셔도 될지는 ..테스트해보지않았습니다.
공부용으로 보실거면 devexpress같은거 걷어내시고 빌드해보시는것도 방법이겠네요 ㅠ 

어쨌든 어느정도 기능 검증이 완료되면 패키징해서 공유드릴게요.

실례지만 어떻게 알고 오셨나요??

**Comment by gellston** [comment]
오늘 classufication 레이블링만 가능하지만... 설치가능한 프로그램 업데이트되었습니다. 관심있으시면 받으셔서 한번 사용해보세요
